services:
  - type: web
    name: chfarms-api
    env: python
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: GOOGLE_SHEET_ID
        value: 1ajWKs867tssC1DqY-miGiLG61eNZIKoZCpv5x-18LvY
      - key: FLASK_ENV
        value: production
