"""Add Q3 durable operations records

Revision ID: a35c21b0309b
Revises: 
Create Date: 2026-09-17 17:18:08.491884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a35c21b0309b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('actor', sa.String(length=80), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('batch_arrival',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('batch_code', sa.String(length=40), nullable=False),
    sa.Column('arrival_date', sa.Date(), nullable=False),
    sa.Column('supplier', sa.String(length=120), nullable=False),
    sa.Column('doc_count', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('feed_type', sa.String(length=80), nullable=False),
    sa.Column('house', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_code')
    )
    op.create_table('feed_record',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('movement_type', sa.String(length=12), nullable=False),
    sa.Column('feed_type', sa.String(length=80), nullable=False),
    sa.Column('quantity_bags', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('batch_code', sa.String(length=40), nullable=True),
    sa.Column('house', sa.String(length=80), nullable=True),
    sa.Column('supplier', sa.String(length=120), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processing_session',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('processing_date', sa.Date(), nullable=False),
    sa.Column('source_batch', sa.String(length=80), nullable=False),
    sa.Column('birds_received', sa.Integer(), nullable=False),
    sa.Column('birds_processed', sa.Integer(), nullable=False),
    sa.Column('birds_rejected', sa.Integer(), nullable=False),
    sa.Column('live_weight_kg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('labor_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('transport_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('utilities_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('packaging_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('inspection_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('other_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processing_item',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('product', sa.String(length=80), nullable=False),
    sa.Column('category', sa.String(length=24), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pack_count', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=24), nullable=False),
    sa.Column('selling_rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['processing_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processing_item')
    op.drop_table('processing_session')
    op.drop_table('feed_record')
    op.drop_table('batch_arrival')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
